// File generated by FlutterFire configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _apiKey = String.fromEnvironment(
    'FIREBASE_API_KEY',
    defaultValue: 'AIzaSyCcCunUfbc7ZyYnVZ11BJy5_BgvmBX03-A',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:647205604247:web:270673ecc68cfd9b2352d2',
    messagingSenderId: '647205604247',
    projectId: 'dueit-f01c4',
    authDomain: 'dueit-f01c4.firebaseapp.com',
    storageBucket: 'dueit-f01c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:647205604247:android:270673ecc68cfd9b2352d2',
    messagingSenderId: '647205604247',
    projectId: 'dueit-f01c4',
    storageBucket: 'dueit-f01c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:647205604247:ios:270673ecc68cfd9b2352d2',
    messagingSenderId: '647205604247',
    projectId: 'dueit-f01c4',
    storageBucket: 'dueit-f01c4.firebasestorage.app',
    iosBundleId: 'com.example.dueit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:647205604247:ios:270673ecc68cfd9b2352d2',
    messagingSenderId: '647205604247',
    projectId: 'dueit-f01c4',
    storageBucket: 'dueit-f01c4.firebasestorage.app',
    iosBundleId: 'com.example.dueit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:647205604247:web:270673ecc68cfd9b2352d2',
    messagingSenderId: '647205604247',
    projectId: 'dueit-f01c4',
    authDomain: 'dueit-f01c4.firebaseapp.com',
    storageBucket: 'dueit-f01c4.firebasestorage.app',
  );
}
